# Generated by Django 4.0.2 on 2022-02-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=220)),
                ('warrety', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=220)),
                ('car_model', models.CharField(blank=True, max_length=220, null=True)),
                ('manufacture_year', models.IntegerField()),
                ('car_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carplan')),
            ],
        ),
    ]
