# Generated by Django 4.0.2 on 2022-02-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carplan',
            old_name='warrety',
            new_name='warrenty',
        ),
    ]
